databases:
  - name: my_postgres_db
    plan: free
    databaseName: myapp_db
    user: myapp_user

services:
- type: web
  name: fastify
  env: node
  runtime: node
  repo: https://github.com/EuRV/fullstack-javascript-project-6
  plan: free
  region: oregon
  buildCommand: make setup
  startCommand: make start-prod
  envVars:
    - key: NODE_ENV
      value: production
    - key: SESSION_SECRET
      generateValue: true
    - key: DATABASE_URL
      fromDatabase:
        name: my_postgres_db
        property: connectionString
  autoDeployTrigger: "off"
version: "1"